### ISSUE TITLE
Could not load file or assembly System.Configuration.ConfigurationManager

### ISSUE THREAD

**Issue by rubin55** [dotnet/try-convert#218] opened 2020-02-07 15:51 UTC
I'm getting the following exception when attempting to run try-convert.exe after dotnet tool install -g try-convert:

```
C:\Users\rubin\Syncthing\Source\RAAF\aeon>try-convert -w Orbital.sln --no-backup
System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Microsoft.Build.Evaluation.ToolsetConfigurationReader..ctor(PropertyDictionary`1 environmentProperties, PropertyDictionary`1 globalProperties)
   at Microsoft.Build.Evaluation.ToolsetReader.ReadAllToolsets(Dictionary`2 toolsets, ToolsetRegistryReader registryReader, ToolsetConfigurationReader configurationReader, PropertyDictionary`1 environmentProperties, PropertyDictionary`1 globalProperties, ToolsetDefinitionLocations locations)
   at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection(ToolsetRegistryReader registryReader, ToolsetConfigurationReader configReader)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, ToolsetDefinitionLocations toolsetDefinitionLocations)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor()
   at MSBuild.Abstractions.MSBuildWorkspace..ctor(ImmutableArray`1 paths, Boolean noBackup) in /_/src/MSBuild.Abstractions/MSBuildWorkspace.cs:line 23
   at MSBuild.Abstractions.MSBuildWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup) in /_/src/MSBuild.Abstractions/MSBuildWorkspaceLoader.cs:line 45
   at MSBuild.Conversion.Program.Run(String project, String workspace, String msbuildPath, Boolean diffOnly, Boolean noBackup) in /_/src/try-convert/Program.cs:line 73
```

**Comment by stijnherreman** [comment] 2020-03-03 14:27
I'm getting this error for a unit test project. The tool converted a regular class library project without any problems.

**Comment by stijnherreman** [comment] 2020-03-03 14:34
This is a duplicate of #169, the solution is to *not* use the Developer Command Prompt or Developer PowerShell.

**Comment by cartermp** [comment] 2020-05-01 17:35
Closing as a duplicate of #169. I'll update the README and other places to make mention of this

**Closed by cartermp** 2020-05-01 17:35 UTC
Labels: duplicate
