### ISSUE TITLE
System.NotSupportedException: This project has custom imports in a manner that's not supported.

### ISSUE THREAD

**Issue by jphellemons** [dotnet/try-convert#275] opened 2020-04-20 08:04 UTC
>System.NotSupportedException: This project has custom imports in a manner that's not supported.
   at MSBuild.Abstractions.MSBuildWorkspace.CreateSdkBaselineProject(String projectFilePath, IProject project, IProjectRootElement root, ImmutableDictionary`2 configurations) in /_/src/MSBuild.Abstractions/MSBuildWorkspace.cs:line 100
   at MSBuild.Abstractions.MSBuildWorkspace..ctor(ImmutableArray`1 paths, Boolean noBackup) in /_/src/MSBuild.Abstractions/MSBuildWorkspace.cs:line 49
   at MSBuild.Abstractions.MSBuildWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup) in /_/src/MSBuild.Abstractions/MSBuildWorkspaceLoader.cs:line 45
   at MSBuild.Conversion.Program.Run(String project, String workspace, String msbuildPath, Boolean diffOnly, Boolean noBackup) in /_/src/try-convert/Program.cs:line 73

I've just run dotnet install -g try-convert
and then try-convert -p pathto.vbproj
and also tried try-convert -w pathto.vbproj

**Comment by jphellemons** [comment] 2020-04-20 08:19
Is it perhaps because of this part in my project file?
```
<Import Project="$(MSBuildToolsPath)\Microsoft.VisualBasic.targets" />
  <PropertyGroup>
    <PostBuildEvent>
    </PostBuildEvent>
  </PropertyGroup>
  <Import Project="$(SolutionDir)\.nuget\NuGet.targets" Condition="Exists('$(SolutionDir)\.nuget\NuGet.targets')" />
```

**Comment by jphellemons** [comment] 2020-04-20 08:24
Also found 
```
<Import Project="..\packages\AutoMapper.3.3.1\tools\AutoMapper.targets" Condition="Exists('..\packages\AutoMapper.3.3.1\tools\AutoMapper.targets')" />
```
but removing that did not fix it

**Comment by jphellemons** [comment] 2020-04-20 10:58
Fixed by opening over 40 vbproj files, removing the RestorePackages tag and two references to nuget.target

**Comment by jmarolf** [comment] 2020-04-20 16:59
I believe this is a duplicate of https://github.com/dotnet/try-convert/issues/124

**Closed by jmarolf** 2020-04-20 16:59 UTC
