### ISSUE TITLE
Could not load file or assembly System.Runtime, Version=5.0.0.0

### ISSUE THREAD

**Issue by markusendres** [dotnet/try-convert#324] opened 2020-11-13 15:56 UTC
I updated to Visual Studio 16.8.00.  
I get the following error when using the try-convert tool to try to convert my solution in the folder. 
`try-convert.exe -w .`
Part of the error message is translated

`try-convert.exe -w .
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK-Resolvertype "WorkloadSdkResolver" could not be loaded. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The System can not find the given file.  C:\Daten\SMS\Core\DSU\DSU.csproj
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

Can any one help me with this issue?
How do I fix it?

**Comment by rjk** [comment] 2020-11-13 19:51
Duplicate of issue #317 which should be fixed by PR #318. 

(I couldn't build from PR #318 but was able to run it using VS)

**Comment by mcolegro** [comment] 2020-11-13 20:00
I've been having this problem today as well.  I have the source locally.  I was able to resolve the issue by changing the TargetFramework to .NET 5.0, on the Try-Convert project and the Smoke.Tests project.

**Comment by cartermp** [comment] 2020-11-16 20:52
Yep, this is a duplicate of #317

**Closed by cartermp** 2020-11-16 20:52 UTC
Labels: duplicate

**Comment by xperiandri** [comment] 2022-03-18 17:46
Still same issue on the .NET 6
```
try-convert --no-backup -p .\GraphDataUploaderSample\GraphDataUploaderSample.csproj -m "C:\Program Files\dotnet\sdk\6.0.201"
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at MSBuild.Abstractions.MSBuildConversionWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb)
   at MSBuild.Conversion.Program.Run(String project, String workspace, String msbuildPath, String tfm, Boolean forceWebConversion, Boolean preview, Boolean diffOnly, Boolean noBackup, Boolean keepCurrentTfms, Boolean update, Boolean mauiConversion) in /_/src/try-convert/Program.cs:line 133
PM> try-convert --no-backup -w .\GraphDataUploaderSample\GraphDataUploaderSample.csproj -m "C:\Program Files\dotnet\sdk\6.0.201"
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at MSBuild.Abstractions.MSBuildConversionWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb)
   at MSBuild.Conversion.Program.Run(String project, String workspace, String msbuildPath, String tfm, Boolean forceWebConversion, Boolean preview, Boolean diffOnly, Boolean noBackup, Boolean keepCurrentTfms, Boolean update, Boolean mauiConversion) in /_/src/try-convert/Program.cs:line 133
```
